# Generated by Django 6.0.1 on 2026-01-16 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('actors', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=32)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('running_time', models.PositiveIntegerField(blank=True, null=True)),
                ('is_from_tmdb', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.movie')),
            ],
        ),
    ]
